### ISSUE TITLE
After Pull, HTM No Longer Works

### ISSUE THREAD

**Issue by jrwoodman** [thisguyistotallyben/hamtheman#5]
WELCOME TO HAM THE MAN
-----
loading config...
  config loaded.
  Username: HamTheMan#1965
  Servers:  1
-----
Ready...
loading extensions...
/home/russ/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py:618: RuntimeWarning: coroutine 'setup' was never awaited
  setup(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/russ/.local/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/russ/bots/hamtheman/./hamtheman.py", line 55, in on_ready
    await self.load_extension(cog)
TypeError: object NoneType can't be used in 'await' expression

**Comment by CzarAlex** [comment]
I have a newer version that may work. it adds the functionality to check for ISS passes based on gridsquare. 
https://github.com/CzarAlex/hamtheman
